brews:
- name: insights
  goarm: 6
  tap:
    owner: FairwindsOps
    name: homebrew-tap
  folder: Formula
  description: Command Line utility for Fairwinds Insights
  test: |
    system "#{bin}/insights version"
builds:
- ldflags:
  - -X github.com/fairwindsops/insights-cli/pkg/version.version={{.Version}} -X github.com/fairwindsops/insights-cli/pkg/version.commit={{.Commit}} -s -w
  # golang.org/x/sys/windows
  # ../go/pkg/mod/golang.org/x/sys@v0.0.0-20200803210538-64077c9b5642/windows/zsyscall_windows.go:2852:38: undefined: WSAData
  # ../go/pkg/mod/golang.org/x/sys@v0.0.0-20200803210538-64077c9b5642/windows/zsyscall_windows.go:3125:51: undefined: Servent
  # ../go/pkg/mod/golang.org/x/sys@v0.0.0-20200803210538-64077c9b5642/windows/zsyscall_windows.go:3139:50: undefined: Servent
  ignore:
  - goos: windows
    goarch: arm64
  main: ./cmd/insights
  goarch:
  - amd64
  - arm
  - arm64
  - 386
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarm:
  - 6
  - 7
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
