version: 2.1

jobs:
  release:
    docker:
      - image: cimg/go:1.15
    steps:
      - checkout
      - run: |
          curl -fsSLo goreleaser.deb https://github.com/goreleaser/goreleaser/releases/download/v0.174.2/goreleaser_amd64.deb
          echo "bad33997ea9977a84196bdca1d5993fada909cd81c3e88d52bd297666bea61a4 goreleaser.deb" | sha256sum -c
          sudo dpkg -i goreleaser.deb
          git checkout -- .
          git clean -df .
          goreleaser

  test:
    docker:
      - image: cimg/go:1.15
    steps:
      - checkout
      - run: |
              go get -u golang.org/x/lint/golint
              go get honnef.co/go/tools/cmd/staticcheck
              go list ./pkg/... | grep -v vendor | xargs golint -set_exit_status
              go list ./pkg/... | grep -v vendor | xargs go vet
              staticcheck ./pkg/...
              go test ./pkg/... -coverprofile=coverage.txt -covermode=count

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - release:
          requires:
          - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/

