version: 2.1
orbs:
  rok8s: fairwinds/rok8s-scripts@12.1.1

references:
  install_vault: &install_vault
    run:
      name: install hashicorp vault
      command: |
        apk --update add curl yq
        cd /tmp
        curl -LO https://releases.hashicorp.com/vault/1.9.2/vault_1.9.2_linux_amd64.zip
        unzip vault_1.9.2_linux_amd64.zip
        mv vault /usr/bin/vault

jobs:
  test:
    working_directory: /home/circleci/go/src/github.com/fairwindsops/insights-cli
    docker:
      # Note the goreleaser version is also referenced in the release and snapshot jobs.
      - image: goreleaser/goreleaser:v2.3.2
    steps:
      - checkout
      - run:
          name: lint
          command: |
            fmt_output=$(go fmt ./...)
            if [ ! -z "$fmt_output" ] ; then
              echo "The go fmt command reports these files need to be formatted, please fix this in the repository."
              echo "$output"
              exit 1
            fi
            go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.62.2
            golangci-lint run -v --timeout 5m0s
      - run: ./.circleci/scripts/e2e-env.sh
      - *install_vault
      - rok8s/get_vault_env:
          vault_path: repo/insights-cli/env
      - run:
          name: test
          command: |
            go test -tags e2e ./...
            go vet ./...
  snapshot:
    working_directory: /go/src/github.com/fairwindsops/insights-cli
    resource_class: large
    docker:
      # Note the goreleaser version is also referenced in the release and test jobs.
      - image: goreleaser/goreleaser:v2.3.2
    steps:
      - checkout
      - setup_remote_docker:
          version: docker24
      - run: goreleaser --snapshot
      # Avoid copying both archive files and the directories used to create them.
      - run: mkdir snapshot-artifacts && cp dist/*.tar.gz dist/*.txt dist/*.rb dist/*.json snapshot-artifacts
      - store_artifacts:
          path: snapshot-artifacts
  release:
    working_directory: /go/src/github.com/fairwindsops/insights-cli
    resource_class: large
    shell: /bin/bash
    docker:
      # Note the goreleaser version is also referenced in the snapshot and test jobs.
      - image: goreleaser/goreleaser:v2.3.2
    steps:
      - checkout
      - run: ./.circleci/scripts/e2e-env.sh
      - *install_vault
      - rok8s/get_vault_env:
          vault_path: repo/global/env
      - rok8s/get_vault_env:
          vault_path: repo/insights-cli/env
      - run: |
              go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.62.2
              golangci-lint run -v --timeout 5m0s
              go test -tags e2e ./pkg/...
      - setup_remote_docker:
          version: docker24
      - rok8s/docker_login:
          registry: "quay.io"
          username: $FAIRWINDS_QUAY_USER
          password-variable: FAIRWINDS_QUAY_TOKEN
      - run: echo 'export GORELEASER_CURRENT_TAG="${CIRCLE_TAG}"' >> $BASH_ENV
      - run: goreleaser

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - snapshot:
          requires:
            - test
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
  release:
    jobs:
      - release:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
