version: 2.1

jobs:
  release:
    resource_class: large
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - run: |
          curl -fsSLo goreleaser.deb https://github.com/goreleaser/goreleaser/releases/download/v0.184.0/goreleaser_amd64.deb
          echo "6bddbabef03e51403568b70989c2ea20c5f021d0cba11411255a287e0f3fec3d goreleaser.deb" | sha256sum -c
          sudo dpkg -i goreleaser.deb
          git checkout -- .
          git clean -df .
          goreleaser

  test:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - run: |
              go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.1
              golangci-lint run -v --timeout 2m0s
              go test ./pkg/... -coverprofile=coverage.txt -covermode=count

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - release:
          requires:
          - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/

