version: 2.1

orbs:
  rok8s: fairwinds/rok8s-scripts@11

references:
  enable_experimental_features: &enable_experimental_docker_features
    run:
      name: enable experimental features
      command: |
        set -ex
        apk --update add openssh
        ssh remote-docker \<<EOF
          sudo bash -c 'echo "{\"experimental\": true}" > /etc/docker/daemon.json'
          sudo systemctl restart docker
        EOF
  install_vault: &install_vault
    run:
      name: install hashicorp vault
      command: |
        apk --update add curl yq
        cd /tmp
        curl -LO https://releases.hashicorp.com/vault/1.9.2/vault_1.9.2_linux_amd64.zip
        unzip vault_1.9.2_linux_amd64.zip
        mv vault /usr/bin/vault

jobs:
  test:
    working_directory: /go/src/github.com/fairwindsops/insights-cli
    docker:
      - image: circleci/golang:1.17
    steps:
      - checkout
      - run:
          name: lint
          command: |
            test -z $(go fmt ./...)
            go install golang.org/x/lint/golint@latest
            golint -set_exit_status ./...
            go get honnef.co/go/tools/cmd/staticcheck
            staticcheck ./pkg/...
      - run:
          name: test
          command: |
            go test ./...
            go vet ./...
  snapshot:
    working_directory: /go/src/github.com/fairwindsops/insights-cli
    resource_class: large
    docker:
      - image: goreleaser/goreleaser:v1.6.3
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      #- *enable_experimental_docker_features
      - run: goreleaser --snapshot
      # Avoid copying both archive files and the directories used to create them.
      - run: mkdir snapshot-artifacts && cp dist/*.tar.gz dist/*.txt dist/*.rb dist/*.json snapshot-artifacts
      - store_artifacts:
          path: snapshot-artifacts
  release:
    working_directory: /go/src/github.com/fairwindsops/insights-cli
    resource_class: large
    shell: /bin/bash
    docker:
      - image: goreleaser/goreleaser:v1.6.3
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      #- *enable_experimental_docker_features
      - *install_vault
      - rok8s/get_vault_env:
          vault_path: repo/global/env
      - rok8s/get_vault_env:
          vault_path: repo/insights-cli/env
      - rok8s/docker_login:
          registry: "quay.io"
          username: $FAIRWINDS_QUAY_USER
          password-variable: FAIRWINDS_QUAY_TOKEN
      - run: echo 'export GORELEASER_CURRENT_TAG="${CIRCLE_TAG}"' >> $BASH_ENV
      - run: goreleaser

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - snapshot:
          requires:
            - test
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
  release:
    jobs:
      - release:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
